#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Oct 02 22:35:29 CST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim alu_sim_time_impl -key {Post-Implementation:sim_1:Timing:alu_sim} -tclbatch alu_sim.tcl -log simulate.log"
xsim alu_sim_time_impl -key {Post-Implementation:sim_1:Timing:alu_sim} -tclbatch alu_sim.tcl -log simulate.log

